module-name: docker-registry
rc-tag: 1.4.0
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/dockerregistry-operator:main
  - europe-docker.pkg.dev/kyma-project/prod/tpi/registry:2.8.1-1ae4c190
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/test/**"
    - "**/*_test.go"
