name: btp integration tests

on:
  workflow_call:

jobs:
  btp-integration-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/btp/hack
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - uses: ./.github/actions/setup-kyma
      - name: Create btp account with kyma enable
        run: |
          sudo ln -sf bash /bin/sh
          echo "$BTP_ENV" > $ENV_PATH
          export $(cat $ENV_PATH | xargs)
          echo "Used env file has $(sed -n '$=' $ENV_PATH) lines"
          TF_VAR_BTP_SUBACCOUNT=btp-test-${{ github.run_id }}-${{ github.run_attempt }}
          tofu -chdir=../tf init
          tofu -chdir=../tf apply -auto-approve
        env:
          ENV_PATH: /tmp/.env
          BTP_ENV: ${{ secrets.BTP_INTEGRATION_TEST }}

      - name: BTP integration test
        shell: bash
        run: |
          sudo ln -sf bash /bin/sh
          echo "$BTP_ENV" > $ENV_PATH
          export $(cat $ENV_PATH | xargs)
          echo "Used env file has $(sed -n '$=' $ENV_PATH) lines"
          ./bootstrap.sh btp-test-${{ github.run_id }}-${{ github.run_attempt }}
                env:
          ENV_PATH: /tmp/.env
          BTP_ENV: ${{ secrets.BTP_INTEGRATION_TEST }}

