name: btp integration tests

on:
  workflow_call:

jobs:
  btp-integration-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/btp/hack
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - name: BTP integration test
        run: |
          echo "$BTP_ENV" > $ENV_PATH
          export $(cat $ENV_PATH | xargs)
          ./bootstrap.sh btp-test-${{ github.run_id }}-${{ github.run_attempt }}
        env:
          ENV_PATH: /tmp/.env
          BTP_ENV: ${{ secrets.BTP_INTEGRATION_TEST }}