name: btp integration tests

on:
  workflow_call:

jobs:
  btp-integration-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/btp/hack
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - uses: ./.github/actions/setup-kyma
        with:
          path: "tests/btp/bin"
      - name: Create btp account with kyma enable
        run: |
          sudo ln -sf bash /bin/sh
          echo "$BTP_ENV" > $ENV_PATH
          export $(cat $ENV_PATH | xargs)
          echo "Used env file has $(sed -n '$=' $ENV_PATH) lines"
          echo "$TF_VAR_BTP_SUBACCOUNT"
          tofu -chdir=../tf init
          tofu -chdir=../tf apply -auto-approve
        env:
          ENV_PATH: /tmp/.env
          BTP_ENV: ${{ secrets.BTP_INTEGRATION_TEST }}
          TF_VAR_BTP_SUBACCOUNT: btp-test-${{ github.run_id }}-${{ github.run_attempt }}

      - name: BTP integration test
        shell: bash
        run: |
          sudo ln -sf bash /bin/sh
          echo "$BTP_ENV" > $ENV_PATH
          export $(cat $ENV_PATH | xargs)
          echo "Used env file has $(sed -n '$=' $ENV_PATH) lines"
          mkdir -p tmp
          ./bootstrap.sh
        env:
          ENV_PATH: /tmp/.env
          BTP_ENV: ${{ secrets.BTP_INTEGRATION_TEST }}

      - name: Test if docker registry is working
        shell: bash
        run: |
          KUBECONFIG=tmp/sa-kubeconfig.yaml make docker_registry_login
          KUBECONFIG=tmp/sa-kubeconfig.yaml make docker_push_simple_app
          KUBECONFIG=tmp/sa-kubeconfig.yaml make deploy_simple_app

      - name: Delete btp account
        run: |
          sudo ln -sf bash /bin/sh
          echo "$BTP_ENV" > $ENV_PATH
          export $(cat $ENV_PATH | xargs)
          echo "Used env file has $(sed -n '$=' $ENV_PATH) lines"
          echo "$TF_VAR_BTP_SUBACCOUNT"
          kubectl delete -n kyma-system -f k8s-resources/dependencies/object-store-binding.yaml kubeconfig=tmp/sa-kubeconfig.yaml 
          kubectl delete serviceinstances.services.cloud.sap.com -n kyma-system object-store-reference kubeconfig=tmp/sa-kubeconfig.yaml
          tofu -chdir=../tf init
          tofu -chdir=../tf destroy -auto-approve
        env:
          ENV_PATH: /tmp/.env
          BTP_ENV: ${{ secrets.BTP_INTEGRATION_TEST }}
          TF_VAR_BTP_SUBACCOUNT: btp-test-${{ github.run_id }}-${{ github.run_attempt }}