name: btp integration tests

on:
  workflow_call:

jobs:
  btp-integration-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/btp/hack
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
      - uses: ./.github/actions/setup-kyma
        with:
          path: "tests/btp/bin"
      - name: Create btp account with kyma enable
        run: |
          sudo ln -sf bash /bin/sh
          echo "$BTP_ENV" > $ENV_PATH
          export $(cat $ENV_PATH | xargs)
          tofu -chdir=../tf init
          tofu -chdir=../tf apply -auto-approve
        env:
          ENV_PATH: /tmp/.env
          BTP_ENV: ${{ secrets.BTP_INTEGRATION_TEST }}
          TF_VAR_BTP_SUBACCOUNT: btp-test-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Generate access
        run: |
          sudo ln -sf bash /bin/sh
          echo "$BTP_ENV" > $ENV_PATH
          export $(cat $ENV_PATH | xargs)
          mkdir -p tmp
          make headless-kubeconfig
          CLUSTERROLE=cluster-admin make service-account-kubeconfig
        env:
          ENV_PATH: /tmp/.env
          BTP_ENV: ${{ secrets.BTP_INTEGRATION_TEST }}
          TF_VAR_BTP_SUBACCOUNT: btp-test-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Add bindings
        run: |
          sudo ln -sf bash /bin/sh
          echo "$BTP_ENV" > $ENV_PATH
          export $(cat $ENV_PATH | xargs)
          KUBECONFIG=tmp/sa-kubeconfig.yaml BTP_PROVIDER_SUBACCOUNT_ID=$TF_VAR_BTP_PROVIDER_SUBACCOUNT_ID make share-sm-service-operator-access
          KUBECONFIG=tmp/sa-kubeconfig.yaml make create-object-store-reference
          KUBECONFIG=tmp/sa-kubeconfig.yaml make enable_docker_registry
        env:
          ENV_PATH: /tmp/.env
          BTP_ENV: ${{ secrets.BTP_INTEGRATION_TEST }}
          TF_VAR_BTP_SUBACCOUNT: btp-test-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Test if docker registry is working
        shell: bash
        run: |
          KUBECONFIG=tmp/sa-kubeconfig.yaml make docker_registry_login
          KUBECONFIG=tmp/sa-kubeconfig.yaml make docker_push_simple_app
          KUBECONFIG=tmp/sa-kubeconfig.yaml make deploy_simple_app

      - name: Delete btp account
        run: |
          echo "Chleb 0"
          sudo ln -sf bash /bin/sh
          echo "Chleb 1"
          echo "$BTP_ENV" > $ENV_PATH
          echo "Chleb 2"
          export $(cat $ENV_PATH | xargs)
          echo "Chleb 3"
          kubectl delete -n kyma-system -f ../k8s-resources/dependencies/object-store-binding.yaml --kubeconfig tmp/sa-kubeconfig.yaml 
          echo "Chleb 4"
          kubectl delete serviceinstances.services.cloud.sap.com -n kyma-system object-store-reference --kubeconfig tmp/sa-kubeconfig.yaml
          echo "Chleb 5"
          tofu -chdir=../tf init
          tofu -chdir=../tf destroy -auto-approve
        env:
          ENV_PATH: /tmp/.env
          BTP_ENV: ${{ secrets.BTP_INTEGRATION_TEST }}
          TF_VAR_BTP_SUBACCOUNT: btp-test-${{ github.run_id }}-${{ github.run_attempt }}