name: integration tests

on:
  workflow_call:
    inputs:
      image:
        description: 'The image to test'
        required: true
        type: string
      trigger_btp:
        description: 'Trigger BTP integration test'
        required: false
        type: boolean
        default: false


jobs:
  operator-integration-test:
    if: ${{ !startsWith(github.event_name, 'pull_request') || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-k3d-cluster
      - name: run test
        run: |
          make -C components/operator deploy
          make -C tests/operator test
        env:
          IMG: ${{ inputs.image }}
      - if: ${{ always() }}
        uses: ./.github/actions/collect-cluster-info

  gardener-integration-test:
    if: ${{ !startsWith(github.event_name, 'pull_request') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-go
      - name: provision gardener
        run: |
          echo "$GARDENER_SA" > $GARDENER_SA_PATH
          echo "Used kubeconfig file has $(sed -n '$=' $GARDENER_SA_PATH) lines"
          make -C hack provision-gardener
        env:
          GARDENER_SECRET_NAME: ${{ secrets.GARDENER_SECRET_NAME }}
          GARDENER_PROJECT: ${{ secrets.GARDENER_PROJECT }}
          GARDENER_SA_PATH: /tmp/gardener-sa.yaml
          GARDENER_SA: ${{ secrets.GARDENER_SA }}
      - name: run test
        run: |
          make -C components/operator deploy
          make -C tests/operator test
        env:
          IMG: ${{ inputs.image }}
      - name: deprovision gardener
        if: ${{ always() }}
        run: make -C hack deprovision-gardener
        env:
          GARDENER_SA_PATH: /tmp/gardener-sa.yaml

  btp-integration-tests:
    if: ${{ inputs.trigger_btp == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/btp/hack
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-kyma
        with:
          path: "tests/btp/bin"
      - name: Create btp account with kyma enable
        run: |
          echo "local test of triggering"